# This is a basic workflow to help you get started with Actions

name: PlatformIO CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        project:
#         - "Projects/WLED"
          - "Projects/ESP_DS18B20_Async_Web_Server"
#          - "Projects/ws2812fx_ap"
#          - "Projects/esp8266_webinterface"
#          - "Projects/forms_led"
#          - "Projects/arduino-blink"
#          - "Projects/arduino-blink_rgb"
#          - "Projects/"
    

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
#      - name: Run a one-line script
#        run: |
#             sudo apt-get install neofetch
#             neofetch
#             #uname -a

      - uses: actions/cache@v3
        with:
          path: |
            #~/.cache/pip
            #~/.platformio
            ~/work/My_PIO_Projects/My_PIO_Projects/Projects/*/.pio
          key: ${{ runner.os }}-pio

#      - name: Set up Python
#        uses: actions/setup-python@v4
#        with:
#          python-version: "3.9"
          
      - name: Install PlatformIO Core
        run: |
          pip install --upgrade platformio
          pio --version

      - name: Build Project
        run: |
          pio run -d ${{ matrix.project}}

      - name: Save and Push Build
        run: |
          mkdir -p ${{matrix.project}}/build_output/
          ls ${{matrix.project}}/.pio/build/*/
          mv -b ${{matrix.project}}/.pio/build/*/firmware.* ${{matrix.project}}/build_output/
          ls -Rlh ${{matrix.project}}/build_output/
          git config user.name github-actions
          git config user.email github-actions@github.com
          if git diff --exit-code; then
             git add ${{matrix.project}}/build_output/
             git commit -am "GH Action Files added $(date +"%d-%m-%y_%T")"
             git push 
          fi

